seguridad:
  opciones:
    activo: false #true/false
    descripcion: Módulo de Seguridad
    imagen: seguridad.gif
    nombre: Seguridad
    urls:
      default:
        modulo: autenticacion.php
        modulo_dev: autenticacion_dev.php
      Reportes:
        absoluta: reportes/reportes/seguridad
    imagenes:
      default: OperatorClass.png
  menu:
    Definiciones:
      #Grupo de Usuarios:
      Empresa:                                              datosempresa
      Usuarios:                                             usuarios
    Procesos:
      Permisologías por Usuario:                            apliuser
      #Perfiles por Grupo de Usuarios
      #Usuarios por Grupo
      #Perfiles de Usuario
    #Reportes:
      #Bitácora de Transacciones:                            segrbitaco
      #Bitácora de Aplicación:                               segrbitapl
      #Bitácora de Usuarios:                                 segrbitusu
      #Accesos por Modulos
      #Accesos por Usuarios
    Mantenimiento:
      Cambiar Contraseña:                                     cambiopasswd
    Reportes:
      Generales:
        Bitacora de Transacciones :                           segrbitaco.php
        Bitacora de Transacciones por Aplicación :          segrbitapl.php
        Bitacora de Transacciones por Usuario/Aplicación :    segrbitusu.php