generator:
  class:              cidesaPropelAdminGenerator
  param:
    model_class:      Cagrucla
    theme:            cidesaGenerator
    fields:
      codgru: { name: Grupo, params: size=25 readOnly=true}
      desgru: { name: Descripción, params: size=60 readOnly=true}
      grid: { name: .}
    list:
      title:  Claúsulas por Grupo
      display: [=codgru, desgru]
      filters: [codgru]
      object_actions:
       _edit:        ~
      actions:
        _create:        NONE
      max_per_page:	  10
      sort:    codgru
    edit:
      title:          Edición de Claúsulas por Grupo
      display:
        "Datos del Grupo":  [codgru, desgru]
        "Datos de las Claúsulas": [_grid]
      actions:
        _list:        ~
        _save:        ~
        _create:        NONE
        _delete:        NONE
