generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Usuarios
    theme:            default
    fields:
      loguse:      { name : Usuario }
      nomuse:     { name : Nombre }
      apluse:     { name : Aplicación }
      numemp:     { name : Número Empleado }
      pasuse:     { name : Contraseña }
      diremp:     { name : Dirección }
      telemp:     { name : Teléfono }
      cedemp:     { name : C.I, params: maxlength=10 }
      numuni:     { name : Unidad }
      codcat:     { name : Código Categoría }
      confirm:    { name : Confirmación de Contraseña}
      codniv:    { name : Nivel de Aprobación}
    list:
      title:          Usuarios
      display:        [=loguse, cedemp, nomuse ]
      filters:        [loguse, cedemp, nomuse]
      max_per_page:   10
      object_actions:
        _edit:        ~
        _delete:      ~
    edit:
      title:          Edición de Usuario
      display:        [loguse, cedemp, nomuse, pasuse, apluse, numemp, diremp, telemp, numuni, codcat, confirm, codniv]
      actions:
        _list:        ~
        _save:        ~
        _delete:      ~
        _create:      ~
