generator:
  class:              cidesaPropelAdminGenerator
  param:
    model_class:      Casolpag
    theme:            cidesaGenerator
    fields:
      solpag: { name: Referencia, params: size=10 maxlength=8 onBlur="javascript: event.keyCode=13; enter1(event,this.value);"}
      fecsol: { name: Fecha, params: date_format='dd/MM/yyyy' maxlength=10}
      dessol: { name: Descripci贸n, type: textarea_tag, params: size=80x5 maxlength=1000 onkeyup="javascript:return ismaxlength(this)"}
      tipcom: { name: Tipo Compromiso, params: maxlength=4}
      nomext: { name: Descripci贸n}
      cedrif: { name: Beneficiario, params: maxlength=15}
      nomben: { name: Descripci贸n}
      monsol: { name: Monto Total, params: readonly=true}
      grid: { name: . }
    list:
      title:          Solicitudes de Pagos
      display:        [=solpag, fecsol]
      object_actions:
        _edit:        ~
        _delete:      ~
      filters:        [solpag, fecsol, cedrif]
      max_per_page:   10
      sort:           solpag
    edit:
      title:          Edici贸n de Solicitud de Pago
      display:
        "Datos": [solpag, _fecsol, dessol, _tipcom, _cedrif, monsol]
        "Imputaciones Presupuestarias": [_grid]
      actions:
        _list:        ~
        _save:        ~
        _delete:      ~
        _create:      ~