default:
  http_metas:
    content-type: text/html

  metas:
    title:        Módulo de Contabilidad
    robots:       index, follow
    description:  Módulo de Contabilidad
    keywords:     Módulo de Contabilidad
    language:     en

  stylesheets:    [main, estilos]

  javascripts:    [ %SF_PROTOTYPE_WEB_DIR%/js/prototype, %SF_PROTOTYPE_WEB_DIR%/js/scriptaculous, tools, observe, ajax, dFilter]
#  javascripts:    [%SF_PROTOTYPE_WEB_DIR%/js/prototype, %SF_PROTOTYPE_WEB_DIR%/js/scriptaculous, ext/adapter/ext/ext-base, ext/adapter/prototype/ext-prototype-adapter, ext/ext-all, gridext.js]

#ext/adapter/ext/ext-base, ext/adapter/prototype/ext-prototype-adapter, ext/ext-all
  has_layout:     on
  layout:         layout