generator:
  class:              cidesaPropelAdminGenerator
  param:
    model_class:      Tsfonant
    theme:            cidesaGenerator
    fields:
      reffon: { name: Número de Recibo, params: maxlength=8 onBlur="javascript:event.keyCode=13; enter(event,this.value);"}
      fecfon: { name: Fecha de Emisión, params: date_format='dd/MM/yyyy' maxlength=10}
      cedrif: { name: C.I/R.I.F del Beneficiario, params: maxlength=15}
      nomben: { name: Nombre del Beneficiario, params: maxlength=250}
      desfon: { name: Concepto, type: textarea_tag, params: size=80x5 maxlength=250 onkeyup="javascript:return ismaxlength(this)"}
      monfon: { name: Neto a Pagar}
      grid: { name: . }
      codfon: { name: Fondo en Anticipo }
    list:
      title:          Salidas de Fondos en Anticipo
      display:        [=reffon, fecfon, cedrif]
      object_actions:
        _edit:        ~
        _delete:      ~
      filters:        [reffon, fecfon, cedrif]
      max_per_page:   10
      sort:           reffon
    edit:
      title:          Edición de Salida de Fondo en Anticipo
      display:
        "Datos del Recibo": [reffon, _codfon, _fecfon, _cedrif]
        "Detalle del Pago": [desfon, _grid, monfon]
      hide: [ctapag, agregabenefi, numcue, tipdoc]
      actions:
        _list:        ~
        _save:        ~
        _delete:      ~
        _create:      ~