generator:
  class:              cidesaPropelAdminGenerator
  param:
    model_class:      Casalalm
    theme:            cidesaGenerator
    fields:
      codsal: { name: Número, params : size=10 maxlength=8  onFocus=readonly(this.id) onBlur="enter(this.value)" }
      fecsal: { name: Fecha}
      codpro:
        name: Contratista de Bienes o Servicio y Cooperativa
        params: maxlength=20
        catalogo:
          catalogoweb: Caprovee_Almsalalm
          clase: Caprovee
          ajax: 1
          parametros: getprincipal="getCodpro" getsecundario="getNompro" campoprincipal="codpro" camposecundario="nompro" campobase = "id"
      dessal: { name: Descripción, params : size=100 maxlength=100  }
      tipmov:
        name: Tipo Movimiento
        params: maxlength=3
        catalogo:
          catalogoweb: Catipsal_Almsalalm
          clase: Catipsal
          ajax: 2
          parametros: getprincipal="getTipmov" getsecundario="getDestipsal" campoprincipal="tipmov" camposecundario="destipsal" campobase = "id"
      monsal: { name: Total, params : readOnly=true}
      codcen:
        name: Centro de Costo
        params: maxlength=4
        catalogo:
          catalogoweb: Cadefcen_Almsolegr
          clase: Cadefcen
          ajax: 3
          parametros: getprincipal="getCodcen" getsecundario="getDescen" campoprincipal="codcen" camposecundario="descen" campobase = "id"
      observ:      { name: Observaciones, type: textarea_tag, params: size=60x5 maxlength=1000 onkeyup='ismaxlength(this)'}
      reqart:
        name: Refiere a Requisición
        params: size=15  maxlength=8
        catalogo:
          catalogoweb: Careqart_Almdes
          clase: Careqart
          ajax: 4
          parametros: getprincipal="getReqart" getsecundario="getDesreq" campoprincipal="reqart" camposecundario="desreq" campobase = "id"
          divupdate: divgrid
      grid:  {  name: .}
    list:
      title:          Salidas de Almacén PDVAL
      filters:        [codsal, fecsal, codpro, codcen]
      display:        [=codsal, fecsal, dessal, codpro, nompro, monsal]
      fields:
      object_actions:
        _edit:          ~
        _delete:        ~
      max_per_page:   10
      sort:           codsal
    edit:
      title:          Salidas de Almacén PDVAL
      display:
        "Datos de la Salida":   [codsal, reqart, _fecsal, codpro, dessal, tipmov, monsal, codcen, observ]
        "Detalle de la Salida":   [ _grid]
      actions:
        _list:        ~
        _save:        ~
        _create:      ~
        _delete:      ~