opciones:                  # Opciones generales
  eliminar:                true
  tabla:                   optipret
  name:                    e
  anchogrid:               900
  ancho:                   600
  filas:                   1
  titulo:                  ' '
  htmltotalfilas:          ' '
1:       # Columna 1
  titulo:                  Tipo
  tipo:                    t
  nombrecampo:             codtip
  esgrabable:              true
  html:                    [size=5 mexlength=3]
2:       # Columna 2
  titulo:                  Descripción
  tipo:                    t
  nombrecampo:             destip
  esgrabable:			   false
  html:                    [size=25 readonly=true]
3:       # Columna 3
  titulo:                  Base para el Cálculo
  tipo:                    m
  esgrabable:              true
  nombrecampo:             base
  esnumerico:              true
  html:                    [size="10"]
4:       # Columna 4
  titulo:                  Monto Retención
  tipo:                    m
  esgrabable:              true
  nombrecampo:             montorete
  esnumerico:              true
  html:                    [size="10"]
5:       # Columna 5
  titulo:                  Modificado
  tipo:                    t
  nombrecampo:             modifi
  esgrabable:              true
  oculta:                  true
  html:                    [size=10]
6:       # Columna 6
  titulo:                  Esta
  tipo:                    t
  nombrecampo:             esta
  esgrabable:              true
  oculta:                  true
  html:                    [size=10]
7:       # Columna 7
  titulo:                  EstaISLR
  tipo:                    t
  nombrecampo:             estaislr
  esgrabable:              true
  oculta:                  true
  html:                    [size=10]
8:       # Columna 8
  titulo:                  Esta1xmil
  tipo:                    t
  nombrecampo:             esta1xmil
  esgrabable:              true
  oculta:                  true
  html:                    [size=10]
9:       # Columna 9
  titulo:                  Porcentaje
  tipo:                    m
  esgrabable:              true
  nombrecampo:             porret
  esnumerico:              true
  oculta:                  true
  html:                    [size="10"]
10:       # Columna 10
  titulo:                  Base Imponible
  tipo:                    m
  esgrabable:              true
  nombrecampo:             basimp
  esnumerico:              true
  oculta:                  true
  html:                    [size="10"]
11:       # Columna 11
  titulo:                  Factor
  tipo:                    m
  esgrabable:              true
  nombrecampo:             factor
  esnumerico:              true
  oculta:                  true
  html:                    [size="10"]
12:       # Columna 12
  titulo:                  Sustraendo
  tipo:                    m
  esgrabable:              true
  nombrecampo:             porsus
  esnumerico:              true
  oculta:                  true
  html:                    [size="10"]
13:       # Columna 12
  titulo:                  Unidad Tributaria
  tipo:                    m
  esgrabable:              true
  nombrecampo:             unitri
  esnumerico:              true
  oculta:                  true
  html:                    [size="10"]