default:
  http_metas:
    content-type: text/html

  metas:
    title:        Módulo Tesorería
    robots:       index, follow
    description:  Módulo Tesorería
    keywords:     Módulo Tesorería
    language:     en

  stylesheets:    [main]

  javascripts:    [ %SF_PROTOTYPE_WEB_DIR%/js/prototype, %SF_PROTOTYPE_WEB_DIR%/js/scriptaculous, tools, ajax, dFilter, observe, tesoreria/paggenretord ]

  has_layout:     on
  layout:         layout
