generator:
  class:              cidesaPropelAdminGenerator
  param:
    model_class:      Cpdefniv
    theme:            cidesaGenerator
    fields:
      coraep:    {name: AEP}
      corprc:    {name: Precompromiso}
      corcom:    {name: Compromiso}
      corcau:    {name: Causado}
      corpag:    {name: Pagado}
      corsoltra: {name: Solicitud de Traslado}
      cortrasla:    {name: Traslado}
      corsoladidis: {name: Solicitud de Adicion/Disminucion}
      coradidis:    {name: Adicion/Disminucion}
      coraju:    {name: Ajuste}
      btnanu:    {name: Anular}
      btneli:    {name: Eliminar}
      conpar:    {name: Nivel de Partidas}

    edit:
      title: Configuracion Generales
      display:
        Correlativos:  [coraep, corprc, corcom, corcau, corpag, corsoltra, cortrasla, corsoladidis, coradidis, coraju]
        Generales:  [btnanu, btneli, _conpar]

      actions:
        _save:        ~
