generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Caajuoc
    theme:            default
    fields:
      ajuoc:      { name : Número, params: maxlegth=8}
      ordcom:     { name : Orden de Compra }
      desord:     { name : Descripción OC }
      fecaju:     { name : Fecha de Ajuste, params: date_format='dd/MM/yyyy' }
      desaju:     { name : Descripción }
      monaju:     { name : Monto }
      codpro:     { name : Contratistas de Bienes o Servicio y Cooperativas }
      nompro:     { name : Nombre Contratistas de Bienes o Servicio y Cooperativas }
    list:
      title:          Ajustes a Ordenes de Compra
      display:        [=ajuoc, ordcom, fecaju, desaju, monaju]
      filters:		  [ajuoc, ordcom, fecaju]
      max_per_page:	  5
      sort:           ajuoc
      object_actions:
        _edit:        ~
        _delete:      NONE
    edit:
      title:          Edición de Ajustes a Ordenes de Compra
      display:        [ajuoc, ordcom, fecaju, desaju, monaju, codpro, nompro]
      actions:
        _list:        ~
        _save:        ~
        _delete:      ~
        _create:      ~