opciones:                  # Opciones generales
  eliminar:                false
  tabla:                   caartord
  anchogrid:               1250
  filas:                   0
  titulo:                  Existencia por Almacenes
  htmltotalfilas:          ' '
1:       # Columna 1
  titulo:                  Cod. Artículo
  tipo:                    t
  nombrecampo:             codart
  html:                    [type="text", size="10", readonly=true ]
#  catalogo:                ['caregart', 'sf_admin_edit_form', {desart: 2} ]
2:       # Columna 2
  titulo:                  Descripción
  tipo:                    t
  nombrecampo:             desart
  html:                    [type="text", size="20", readonly=true ]
3:       # Columna 3
  titulo:                  Categoría
  tipo:                    t
  nombrecampo:             codcat
  html:                    [type="text", size="10", readonly=true ]
4:       # Columna 4
  titulo:                  Cant. Ajustada
  tipo:                    m
  nombrecampo:             canaju
  esgrabable:              true
  esnumerico:              true
  html:                    [type="text", size="10" ]
#  jscript:                 'onBlur ="ValidarMontoGrid(this.id),validarRango(this.id)"'
  ajaxfila:                true
  ajaxadicionales:         {0: caajuoc_ordcom}
5:
  titulo:                  Cant. Ordenada
  tipo:                    m
  esgrabable:              true
  nombrecampo:             canord
  esnumerico:              true
  html:                    [type="text", size="10", readonly=true ]
6:
  titulo:                  Unidad de Medida
  tipo:                    t
  nombrecampo:             unimed
  html:                    [type="text", size="10", readonly=true ]
7:
  titulo:                  Costo
  tipo:                    m
  nombrecampo:             cosart
  esnumerico:              true
  html:                    [type="text", size="10", readonly=true ]
8:
  titulo:                  Monto Ajuste
  tipo:                    m
  nombrecampo:             monaju
  esnumerico:              true
  html:                    [type="text", size="10", readonly=true ]
9:
  titulo:                  Monto Recargo
  tipo:                    m
  nombrecampo:             monrecaju
  esnumerico:              true
  html:                    [type="text", size="10", readonly=true ]
10:
  titulo:                  Monto Total
  tipo:                    m
  nombrecampo:             montotaju
  esnumerico:              true
  html:                    [type="text", size="10", readonly=true ]
  estotal:                 [true, caajuoc_monaju]
