default:
  http_metas:
    content-type: text/html

  metas:
    title:        Cidesa - Apertura de Período
    robots:       index, follow
    description:  symfony project
    keywords:     symfony, project
    language:     en

  stylesheets:    [siga]

  javascripts:    [ %SF_PROTOTYPE_WEB_DIR%/js/prototype, %SF_PROTOTYPE_WEB_DIR%/js/scriptaculous ]

  has_layout:     on
  layout:         layout_seguridad
