generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Opdefemp
    theme:            default

    fields:
      codemp:      { name: Cod. Empresa }
      nomemp:      { name: Nombre }
      diremp:      { name: Dirección }
      ctapag:      { name: Cuenta por Pagar  }
      ctades:      { name: Cuenta de Descuento  }
      numini:      { name: Número Inicial para la Orden de Pago   }
      forubi:      { name: Formato Unidad Origen   }
      ordnom:      { name: Nómina  }
      ordobr:      { name: Aportes  }
      tipeje:      { name: Ejecutivo  }
      ordliq:      { name: Liquidación  }
      ordfid:      { name: Fideicomiso  }
      ordval:      { name: Obras  }
      unitri:      { name: Valor de la Unidad Tributaria  }
      genctaord:   { name: Activar}
      gencomadi:   { name: Activar}
      vercomret:   { name: Comprobantes y Retenciones  }
      gencaubon:   { name: Activar}
      genordret:   { name: Generar Orden de Pago de Retenciones despues de guardar la Orden de Pago}
      emichepag:   { name: Mostrar sólo Órdenes de Pago con cheque entregado (Fondos a Terceros)}
      cuecajchi:   { name: Cuenta Bancaria}
      nomcuecajchi:  { name: Cuenta Bancaria}
      tipcajchi:   { name: Movimiento de Salida}
      nomtipcajchi:  { name: Movimiento de Salida}
      monapecajchi:  { name: Monto de Apertura}
      porrepcajchi:  { name: Porcentaje de Reposición}
      tiprencajchi:  { name: Movimiento de Rendición}
      nomtiprencajchi:  Movimiento de Rendicion}
      numinicajchi:  { name: N° Inicial Caja Chica}
      cedrifcajchi:  { name: Beneficiario}
      nomben:  { name: Beneficiario}
      codcatcajchi:  { name: Código Categoría}
      nomcat:  { name: Nombre}
      gencomalc:  { name: Genera Comprobantes a Institutos Gubernamentales}
      reqaprord:  { name: Requiere Aprobación}
      ordcomptot:  { name: Refiere a Compromiso  Total}
      ordmotanu:  { name: Solicita Motivo de Anulación}
      ordconpre:  { name: Colocar el Prefijo OP en el Comprobante}
      manbloqban:  { name: Maneja Bloqueos de Cuentas Bancarias}
      ordret:    { name: Retenciones  }
      ordtna:    { name: Tesoreria Nacional  }
      ordtba:    { name: Transferencias Bancarias  }
      ordcre:    { name: Desembolsos de Creditos  }
      ordsolpag:    { name: Solicitudes de Pago  }  
      monche:    { name: Monto Max. Emitir un Cheque  }
    list:
      title:          Definición de Empresa
      display:        [=codemp, nomemp, diremp]
      filters:        [codemp]
      sort:           codemp
      max_per_page:   10
    edit:
      title:          Definición de Empresa
      display:        [codemp, nomemp, diremp, ctapag, nomctapag, ctades, nomctades, numini, forubi, ordnom, ordobr, tipeje, ordliq, ordfid, ordval, unitri, genctaord, gencomadi, gencaubon, vercomret, genordret, emichepag, cuecajchi, nomcuecajchi, tipcajchi, nomtipcajchi, monapecajchi, porrepcajchi, tiprencajchi, nomtiprencajchi, numinicajchi, cedrifcajchi, nomben, codcatcajchi, nomcat, gencomalc, reqaprord, ordcomptot, ordmotanu, manbloqban, ordret, ordconpre, ordtna, ordtba, ordcre, monche, ordsolpag]
      fields:
        genctaord:  {type: checkbox_tag}
        gencomadi: {type: checkbox_tag}
        vercomret: {type: checkbox_tag}
        gencaubon: {type: checkbox_tag}
        gencomalc: {type: checkbox_tag}
        manbloqban: {type: checkbox_tag}
      actions:
        _save:        ~