opciones:                  # Opciones generales
  eliminar:                true
  tabla:                   tsdetsal
  anchogrid:               900
  ancho:                   900
  filas:                   25
  titulo:                  ' '
  htmltotalfilas:          ' '
1:       # Columna 1
  titulo:                  C贸digo
  tipo:                    t
  nombrecampo:             codart
  esgrabable:              true
  html:                    [size="20"]
2:       # Columna 2
  titulo:                  Descripci贸n
  tipo:                    t
  nombrecampo:             desart
  html:                    [size="40", readonly=true]
3:       # Columna 3
  titulo:                  C贸d. Categoria
  tipo:                    t
  nombrecampo:             codcat
  esgrabable:              true
  html:                    [size="20"]
4:       # Columna 4
  titulo:                  Monto
  tipo:                    m
  esgrabable:              true
  nombrecampo:             monsal
  esnumerico:              true
  html:                    [size="10"]
5:        # Columna 5
  titulo:                  IVA
  tipo:                    m
  esgrabable:              true
  nombrecampo:             monrec
  esnumerico:              true
  oculta:                  true
  html:                    [size="10"]
6:        # Columna 6
  titulo:                  Monto Total
  tipo:                    m
  esgrabable:              true
  nombrecampo:             totsal
  oculta:                  true
  esnumerico:              true
  html:                    [size="10", readonly=true]
7:       # Columna 7
  titulo:                  C贸digo Partida
  tipo:                    t
  nombrecampo:             codpar
  esgrabable:              true
  oculta:                  true
  html:                    [size="20" readonly=true]