opciones:                  # Opciones generales
  name:                    b
  eliminar:                true
  tabla:                   atgrufam
  anchogrid:               750
  ancho:                   700
  filas:                   7
  titulo:                  ' '
  htmltotalfilas:          ' '
1:       # Columna 1
  titulo:                  Cedula
  tipo:                    t
  nombrecampo:             cedfam
  html:                    [ size="10" ]
  esgrabable:              true
2:       # Columna 2
  titulo:                  Nombre
  tipo:                    t
  nombrecampo:             nomfam
  html:                    [size="20" ]
  esgrabable:              true
3:       # Columna 3
  titulo:                  Apellido
  tipo:                    t
  nombrecampo:             apefam
  html:                    [ size="20" ]
  esgrabable:              true
4:       # Columna 4
  titulo:                  Edad
  tipo:                    m
  nombrecampo:             edad
  html:                    [size="5" ]
  esgrabable:              true
  esnumerico:              true
5:       # Columna 5
  titulo:                  Parentesco
  tipo:                    t
  nombrecampo:             parfam
  html:                    [size="10" ]
  esgrabable:              true
6:
  titulo:                  Ocupacion
  tipo:                    t
  nombrecampo:             ocufam
  html:                    [size="15" ]
  esgrabable:              true
7:       # Columna 4
  titulo:                  Ingresos
  tipo:                    m
  nombrecampo:             moning
  html:                    [size="5" ]
  esgrabable:              true
  esnumerico:              true


