generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Carancot
    theme:            default
    fields:
      candes:  {  name: Desde[UT]}
      canhas:  {  name: Hasta[UT]}
      cancot:  {  name: Cantidad de Cotizaciones}
    list:
      title:          Definición de Rangos de Cotizaciones
      display:        [=candes, canhas, cancot]
      object_actions:
        _edit:        ~
        _delete:      ~
      filters:        [candes, canhas, cancot]
      max_per_page:   10
      sort:           candes
    edit:
      title:          Definición de Rangos de Cotizaciones
      fields:
        candes:  { params: maxlength=10 }
        canhas:  { params: maxlength=10 }
        cancot:  { params: maxlength=3 }
      display:        [candes, canhas, cancot]
      actions:
        _list:         ~
        _save:         ~
        _delete:       ~
        _create:       ~

