generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Tstipren
    theme:            default
    fields:
      codtip: { name: C贸digo, params: maxlength=3}
      destip: { name: Descripci贸n, params: maxlength=50}
    list:
      title:          Definici贸n de Tipos de Rendimiento
      filters:        [codtip, destip]
      display:        [=codtip, destip]
      sort:           codtip
      max_per_page:   10
      object_actions:
        _edit:        ~
        _delete:      ~
      sort:  codtip
    edit:
      title:          Edici贸n de Tipos de Rendimiento
      filters:        [codtip, destip]
      actions:
        _list:        ~
        _save:        ~
        _create:      ~
        _delete:      ~
