opciones:                  # Opciones generales
  name:                    a
  eliminar:                false
  tabla:                   cpdisfuefin
  anchogrid:               850
  ancho:                   1050
  filas:                   1
  titulo:                  ' '
  htmltotalfilas:          ' '
1:       # Columna 1
  titulo:                  F/Financiamiento
  tipo:                    a
  nombrecampo:             origenfin
  esgrabable:              true
  html:                    [size="25x1", readonly=true ]
2:       # Columna 2
  titulo:                  Asignado
  tipo:                    m
  nombrecampo:             monasi
  esgrabable:              true
  html:                    [size="15", readonly=true ]
3:       # Columna 3
  titulo:                  Solictud Traslados
  tipo:                    m
  nombrecampo:             monsoltra
  esgrabable:              false
  oculta:                  true
  html:                    [size="15", readonly=true ]
4:       # Columna 4
  titulo:                  Traslados/Disminuciones
  tipo:                    m
  nombrecampo:             montra
  esgrabable:              true
  html:                    [size="15", readonly=true ]

5:       # Columna 5
  titulo:                  Asignacion Actual
  tipo:                    m
  nombrecampo:             asignactual
  esgrabable:              true
  html:                    [size="15", readonly=true ]
6:       # Columna 6
  titulo:                  Precomprometido
  tipo:                    m
  nombrecampo:             monpre
  esgrabable:              true
  html:                    [size="15", readonly=true ]
7:       # Columna 7
  titulo:                  Comprometido
  tipo:                    m
  nombrecampo:             moncom
  esgrabable:              true
  html:                    [size="15", readonly=true ]
8:       # Columna 8
  titulo:                  Causado
  tipo:                    m
  nombrecampo:             moncau
  esgrabable:              true
  html:                    [size="15", readonly=true ]
9:       # Columna 9
  titulo:                  Pagado
  tipo:                    m
  nombrecampo:             monpag
  esgrabable:              true
  html:                    [size="15", readonly=true ]
10:       # Columna 10
  titulo:                  Disponible
  tipo:                    m
  nombrecampo:             mondisf
  esgrabable:              true
  html:                    [size="15", readonly=true ]
