generator:
  class:              cidesaPropelAdminGenerator
  param:
    model_class:      Cabanco
    theme:            cidesaGenerator
    fields:
      codban:      {name: Código, params: onBlur='this.value=this.value.pad(4, "0",0);' size=4 maxlength=4 }
      desban:      {name: Descripción, type: textarea_tag, params: size=40x2 maxlength=50    }

    list:
      title:   Definicion de Banco
      display:        [=codban, desban]
      filters:		  [codban, desban]
      max_per_page:	  10
      object_actions:
        _edit:        ~
        _delete:      ~
      sort:    codban

    edit:
      title:  Definicion de Banco
      actions:
        _list:        ~
        _save:        ~
        _delete:      ~
        _create:      ~