opciones:                  # Opciones generales
  name:                    a
  eliminar:                false
  tabla:                   Cainvfis
  anchogrid:               900
  ancho:                   850
  filas:                   0
  titulo:                  ' '
  htmltotalfilas:          ' '
1:       # Columna 1
  titulo:                  Código Articulo
  tipo:                    t
  nombrecampo:             codart
  esgrabable:              true
  html:                    [ readonly=true ]
2:       # Columna 2
  titulo:                  Descripción
  tipo:                    t
  nombrecampo:             desart
  esgrabable:              false
  html:                    [ readonly=true size=40]
3:       # Columna 3
  titulo:                  Fecha Inventario
  tipo:                    t
  nombrecampo:             fecinv
  esgrabable:              true
  html:                    [readonly=true size=10]
4:       # Columna 4
  titulo:                  Código Almacen
  tipo:                    t
  nombrecampo:             codalm
  esgrabable:              true
  html:                    [ readonly=true size=10 ]
5:       # Columna 5
  titulo:                  Descripción
  tipo:                    t
  nombrecampo:             desalm
  esgrabable:              false
  html:                    [ readonly=true size=40 ]
4:       # Columna 4
  titulo:                  Código Ubicación
  tipo:                    t
  nombrecampo:             codubi
  esgrabable:              true
  html:                    [ readonly=true size=10 ]
6:       # Columna 5
  titulo:                  Descripción
  tipo:                    t
  nombrecampo:             desubi
  esgrabable:              false
  html:                    [ readonly=true size=40 ]
7:       # Columna 6
  titulo:                  Presentación
  tipo:                    t
  nombrecampo:             presen
  esgrabable:              true
  html:                    [ readonly=true size=10]
8:       # Columna 1
  titulo:                  Relación por Unidad
  tipo:                    m
  nombrecampo:             reluni
  esgrabable:              true
  html:                    [ readonly=true size=10]
9:       # Columna 2
  titulo:                  Total Unidades
  tipo:                    m
  nombrecampo:             exiact
  esgrabable:              true
  html:                    [ readonly=true size=10]