default:
  http_metas:
    content-type: text/html

  metas:
    title:        Cidesa - Tablas a Limpiar
    robots:       index, follow
    description:  Aplicación Maestra
    keywords:     Aplicación Maestra
    language:     en

  stylesheets:    [siga]

  javascripts:    [ %SF_PROTOTYPE_WEB_DIR%/js/prototype, %SF_PROTOTYPE_WEB_DIR%/js/scriptaculous, tools, observe, ajax, dFilter]

  has_layout:     on
  layout:         layout_seguridad
