generator:
  class:              cidesaPropelAdminGenerator
  param:
    model_class:      Cpdeftit
    theme:            cidesaGenerator
    fields:
     codpre: { name: Código }
     codigo1: { name: Código }
     nompre: { name: Descripción }
     nombre1: { name: Descripción }
     grid:   { name: . }
     botones: {name: .}


    edit:
      title: Asignar Clasificador de Partidas
      display:
        Catégoria Presupuestaria Orígen: [ _codpre]
        Catégoria Presupuestaria Destino: [_codigo1]
        Partidas Seleccionadas: [ _botones, _grid ]
      actions:
        _delete:      ~
        _save:        ~
