default:
  http_metas:
    content-type: text/html

  metas:
    title:        Módulo de Presupuesto
    robots:       index, follow
    description:  Módulo de Presupuesto
    keywords:     Módulo de Presupuesto
    language:     en

  stylesheets:    [main]

  javascripts:    [%SF_PROTOTYPE_WEB_DIR%/js/prototype]

  has_layout:     on
  layout:         layout_generales

