generator:
  class:              cidesaPropelAdminGenerator
  param:
    model_class:      Atrecaud
    theme:            cidesaGenerator

    fields:
      codrec:      { name: C贸digo, params: size=12 maxlength=12 }
      desrec:      { name: Descripci贸n, params: size=50 maxlength=50 }
    list:
      title:          Definici贸n de Requisitos de Pacientes
      display:        [=codrec, desrec]
      object_actions:
        _edit:        ~
        _delete:      ~
      filters:        [codrec, desrec]
      max_per_page:   5
      sort:  codrec
    edit:
      title:          Edici贸n de Requisitos de Pacientes
      display:        [codrec, desrec, _requerido ]
      actions:
        _list:        ~
        _save:        ~
        _delete:      ~
        _create:      ~