generator:
  class:              cidesaPropelAdminGenerator
  param:
    model_class:      Cpartley
    theme:            cidesaGenerator
    fields:
      codart:  {name: Código, params: onBlur=rellenar() maxlength=3 size=4 }
      desart:  {name: Descripción}
      nomabr:  {name: Nombre Abreviado, params: maxlength=4 size=5}
      niveles: {name: Aprobación de}
    list:
      title:   Artículos de Ley
      display: [=codart, desart]
      filters: [codart, desart]
    edit:
      title:                       Artículos de Ley
      display:
        Datos del Documento:       [codart, desart, nomabr, _niveles]
      actions:
        _list:        ~
        _create:      ~
        _save:        ~
        _delete:      ~