generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Optipret
    theme:            default
    fields:
      codtip: { name: Código , params: maxlength=3}
      destip: { name: Descripción, params: maxlength=250}
      codcon: { name: Código Contable, params: maxlength=32}
      basimp: { name: Base Imponible}
      porret: { name: Porcentaje a Retener}
      unitri: { name: Unidades Tributarias}
      porsus: { name: Porc. Sustraendo}
      factor: { name: Factor}
      descta: { name: Descripción}
      consustra: { name: Maneja Sustraendo}
      codtipsen: { name: Codificación SENIAT , params: maxlength=3}
    list:
      title:          Tipos de Retenciones
      filters:        [codtip, destip]
      display:        [=codtip, destip, codcon]
      max_per_page:	  5
      sort: codtip
      object_actions:
        _edit:        ~
        _delete:      ~
    edit:
      title:          Tipos de Retenciones
      display:        [codtip, destip, codcon, basimp, porret, unitri, porsus, factor, descta, consustra, codtipsen]
      actions:
        _list:        ~
        _save:        ~
        _create:      ~
        _delete:      ~