opciones:                  # Opciones generales
  name:                    a
  eliminar:                true
  tabla:                   contabc1
  anchogrid:               750
  ancho:                   700
  filas:                   0
  titulo:                  ' '
  htmltotalfilas:          ' '
1:       # Columna 1
  titulo:                  Código de la cuenta
  tipo:                    t
  nombrecampo:             codcta
  html:                    [size="15"]
  oculta:                  false
  esgrabable:              false
2:       # Columna 2
  titulo:                  Descripción del asiento
  tipo:                    t
  nombrecampo:             desasi
  html:                    [size="30"]
  oculta:                  false
  esgrabable:              false
3:       # Columna 3
  titulo:                  Referencia
  tipo:                    t
  nombrecampo:             refasi
  html:                    [size="10"]
  esgrabable:              false
4:       # Columna 4
  titulo:                  Débitos
  tipo:                    m
  nombrecampo:             mondebito
  html:                    [size="10" onBlur=validaMontos(this.id,this);]
  esgrabable:              false
  estotal:                 [true, contabc_totdeb]
5:       # Columna 5
  titulo:                  Créditos
  tipo:                    m
  nombrecampo:             moncredito
  html:                    [size="10" onBlur=validaMontos(this.id,this);]
  esgrabable:              false
  estotal:                 [true, contabc_totcre]