opciones:                  # Opciones generales
  name:                    a
  eliminar:                true
  tabla:                   contabc1
  anchogrid:               700
  ancho:                   600
  filas:                   7
  titulo:                  ' '
  htmltotalfilas:          ' '
1:       # Columna 1
  titulo:                  Código de la cuenta
  tipo:                    t
  nombrecampo:             codcta
  html:                    [size="15"]
  oculta:                  false
  esgrabable:              true
  #ajaxfila:               true
  catalogo:                [ contabc1, sf_admin_edit_form, { codcta : 2 , desasi : 3 }, Contabc1_Confincom ]
2:       # Columna 2
  titulo:                  Descripción del asiento
  tipo:                    t
  nombrecampo:             desasi
  html:                    [size="30"]
  oculta:                  false
  esgrabable:              true
3:       # Columna 3
  titulo:                  Referencia
  tipo:                    t
  nombrecampo:             refasi
  html:                    [size="10"]
  esgrabable:              false
4:       # Columna 4
  titulo:                  Débitos
  tipo:                    m
  nombrecampo:             mondebito
  html:                    [size="10" onBlur=validaMontos(this.id,this);]
  esgrabable:              false
  #ajaxfila:               true
  estotal:                 [true, contabc_totdeb]
5:       # Columna 5
  titulo:                  Créditos
  tipo:                    m
  nombrecampo:             moncredito
  html:                    [size="10" onBlur=validaMontos(this.id,this);]
  esgrabable:              false
  estotal:                 [true, contabc_totcre]

