opciones:                  # Opciones generales
  name:                    a
  eliminar:                false
  tabla:                   caartsol
  anchogrid:               1000
  ancho:                   1200
  filas:                   0
  titulo:                  'Detalle de la Solicitud'
  htmltotalfilas:          ' '
1:       # Columna 1
  titulo:                  Articulo
  tipo:                    t
  nombrecampo:             codart
  html:                    [size="20" disabled=true]
  esgrabable:              false
2:       # Columna 2
  titulo:                  Descripción
  tipo:                    a
  nombrecampo:             desart
  html:                    [size="40x2" disabled=true]
  esgrabable:              false
3:       # Columna 3
  titulo:                  Categoria
  tipo:                    t
  nombrecampo:             codcat
  html:                    [size="15" disabled=true]
  esgrabable:              false
4:       # Columna 4
  titulo:                  Cant. Requerida
  tipo:                    m
  nombrecampo:             canreq
  html:                    [size="10" disabled=true]
  esgrabable:              false
5:       # Columna 5
  titulo:                  Cant. Recibida
  tipo:                    m
  nombrecampo:             canord
  html:                    [size="10" disabled=true]
  esgrabable:              false
6:       # Columna 6
  titulo:                  Costo
  tipo:                    m
  nombrecampo:             costo
  html:                    [size="10" disabled=true]
  esgrabable:              false
7:       # Columna 7
  titulo:                  Recargo
  tipo:                    m
  nombrecampo:             monrgo
  html:                    [size="10" disabled=true]
  esgrabable:              false
8:       # Columna 8
  titulo:                  Total
  tipo:                    m
  nombrecampo:             montot
  html:                    [size="10" disabled=true]
  esgrabable:              false
9:       # Columna 9
  titulo:                  Código Presupuestario
  tipo:                    t
  nombrecampo:             codigopre
  html:                    [size="20" disabled=true]
  esgrabable:              false