generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Aplicacion
    theme:            default
    fields:
      codapl: {name: C贸digo, params: maxlength=3}
      nomapl: {name: Nombre, params: maxlength=50}
      nomyml: {name: Archivo .yml, params: maxlength=50}
    list:
      title:          M贸dulos
      filters:        [codapl, nomapl]
      display:        [=codapl, nomapl, nomyml]
      object_actions:
        _edit:        ~
        _delete:      ~
      max_per_page:   10
      sort: codapl
    edit:
      title:          Edici贸n de M贸dulos
      display:        [codapl, nomapl, nomyml]
      actions:
        _list:        ~
        _save:        ~
        _delete:      ~
        _create:      ~