generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Catipent
    theme:            default
    fields:
      codtipent:  {  name: C贸digo, params: maxlength=3}
      destipent:  {  name: Descripci贸n, params: maxlength=50}
    list:
      title:          Definici贸n de Tipos de Entrada
      display:        [=codtipent, destipent]
      filters:        [codtipent, destipent]
      object_actions:
        _edit:        ~
        _delete:      ~
      max_per_page:   5
      sort:           codtipent
    edit:
      title:          Definici贸n de Tipos de Entrada
      display:		  [codtipent, destipent]
      actions:
        _list:        ~
        _save:        ~
        _delete:      ~
        _create:      ~