propel:
  _attributes: { noXsd: false, defaultIdMethod: native, package: lib.model }
  acunidad:
    numuni:
      type: VARCHAR
      size: 4
      required: true
      ##primaryKey: true
    nomuni:
      type: VARCHAR
      size: 30
      required: true
    desuni:
      type: VARCHAR
      size: 200
    id:
      type: INTEGER
      required: true
      autoIncrement: true
