propel:
  _attributes: { noXsd: false, defaultIdMethod: native, package: lib.model.contabilidad }
  contaba:
    _attributes: { description: Configuración del módulo de contabilidad }
    codemp:
      type: VARCHAR
      size: 3
      required: true
      description: Código Empresa
    loncta:
      type: NUMERIC
      size: 2
      required: true
      description: Longitud de la cuenta
    numrup:
      type: NUMERIC
      size: 2
      required: true
    forcta:
      type: VARCHAR
      size: 32
      required: true
    sitfin:
      type: VARCHAR
      size: 32
    sitfis:
      type: VARCHAR
      size: 32
    ganper:
      type: VARCHAR
      size: 32
    ejepre:
      type: VARCHAR
      size: 32
    hacmun:
      type: VARCHAR
      size: 32
    ctlgas:
      type: VARCHAR
      size: 32
    ctling:
      type: VARCHAR
      size: 32
    fecini:
      type: DATE
      required: true
    feccie:
      type: DATE
      required: true
    codtes:
      type: VARCHAR
      size: 32
    codhac:
      type: VARCHAR
      size: 32
    codpre:
      type: VARCHAR
      size: 32
    codord:
      type: VARCHAR
      size: 32
    codtesact:
      type: VARCHAR
      size: 32
    codhacact:
      type: VARCHAR
      size: 32
    codhacpat:
      type: VARCHAR
      size: 32
    codtespas:
      type: VARCHAR
      size: 32
    codhacpas:
      type: VARCHAR
      size: 32
    codind:
      type: VARCHAR
      size: 32
    codinh:
      type: VARCHAR
      size: 32
    codegd:
      type: VARCHAR
      size: 32
    codegh:
      type: VARCHAR
      size: 32
    codres:
      type: VARCHAR
      size: 32
    codejepre:
      type: VARCHAR
      size: 32
    codctd:
      type: VARCHAR
      size: 32
    codcta:
      type: VARCHAR
      size: 32
    codresant:
      type: VARCHAR
      size: 32
    etadef:
      type: VARCHAR
      size: 1
    codctagas:
      type: VARCHAR
      size: 32
    codctaban:
      type: VARCHAR
      size: 32
    codctaret:
      type: VARCHAR
      size: 32
    codctaben:
      type: VARCHAR
      size: 32
    codctaart:
      type: VARCHAR
      size: 32
    codctagashas:
      type: VARCHAR
      size: 32
    codctabanhas:
      type: VARCHAR
      size: 32
    codctarethas:
      type: VARCHAR
      size: 32
    codctabenhas:
      type: VARCHAR
      size: 32
    codctaarthas:
      type: VARCHAR
      size: 32
    codctapageje:
      type: VARCHAR
      size: 32
    codctaingdevn:
      type: VARCHAR
      size: 32
    codctaingdev:
      type: VARCHAR
      size: 32
    unidad:
      type: VARCHAR
      size: 10
    corcomp:    #Correlativo Comprobante
      type: VARCHAR
      size: 100
    btnelicomanu:    #Boton de Eliminar comprobantes anulados
      type: BOOLEAN
      default: false
    btnmodcom:    #Boton que permite Modificar los Comprobante generado por otros modulos
      type: BOOLEAN
      default: true
    id:
      type: INTEGER
      required: true
      primaryKey: true
      autoIncrement: true
      description: Identificador Único del registro
  contaba1:
    fecini:
      type: DATE
      required: true
    feccie:
      type: DATE
      required: true
    pereje:
      type: VARCHAR
      size: 2
      required: true
    fecdes:
      type: DATE
      required: true
    fechas:
      type: DATE
      required: true
    status:
      type: VARCHAR
      size: 1
      default: A
    id:
      type: INTEGER
      required: true
      primaryKey: true      
      autoIncrement: true
  contabb:
    codcta:
      type: VARCHAR
      size: 32
      required: true
    descta:
      type: VARCHAR
      size: 250
      required: true
    fecini:
      type: DATE
      required: true
    feccie:
      type: DATE
      required: true
    salant:
      type: NUMERIC
      size: 14
      scale: 2
    debcre:
      type: VARCHAR
      size: 1
      required: true
    cargab:
      type: VARCHAR
      size: 1
      required: true
    salprgper:
      type: NUMERIC
      size: 14
      scale: 2
    salacuper:
      type: NUMERIC
      size: 14
      scale: 2
    salprgperfor:
      type: NUMERIC
      size: 14
      scale: 2
    id:
      type: INTEGER
      required: true
      primaryKey: true      
      autoIncrement: true
  contabb1:
    codcta:
      type: VARCHAR
      size: 32
      required: true
      foreignTable: contabb
      foreignReference: codcta
    fecini:
      type: DATE
      required: true
    feccie:
      type: DATE
      required: true
    pereje:
      type: VARCHAR
      size: 2
      required: true
    totdeb:
      type: NUMERIC
      size: 14
      scale: 2
    totcre:
      type: NUMERIC
      size: 14
      scale: 2
    salact:
      type: NUMERIC
      size: 14
      scale: 2
    salprgper:
      type: NUMERIC
      size: 14
      scale: 2
    salprgperfor:
      type: NUMERIC
      size: 14
      scale: 2
    id:
      type: INTEGER
      required: true
      primaryKey: true
      autoIncrement: true
      description: Identificador Único del registro
  contabc:
    numcom:
      type: VARCHAR
      size: 8
      required: true
    feccom:
      type: DATE
      required: true
    descom:
      type: VARCHAR
      size: 1000
    moncom:
      type: NUMERIC
      size: 14
      scale: 2
    stacom:
      type: VARCHAR
      size: 1
      required: true
    tipcom:
      type: VARCHAR
      size: 3
    reftra:
      type: VARCHAR
      size: 8
    loguse:
      type: VARCHAR
      size: 50
    usuanu:
      type: VARCHAR
      size: 50
    id:
      type: INTEGER
      required: true
      primaryKey: true
      autoIncrement: true
      description: Identificador Único del registro

  contabc1:
    _attributes: { description: Detalle de los comprobantes contables }
    numcom:
      type: VARCHAR
      size: 8
      required: true
      foreignTable: contabc           # Tabla foranea
      foreignReference: numcom   # Campo de la tabla foranea
      description: Número de Comprobante
    feccom:
      type: DATE
      required: true
      description: Fecha del comprobante
    debcre:
      type: VARCHAR
      size: 1
      required: true
      description: Débito o Crédito
    codcta:
      type: VARCHAR
      size: 32
      required: true
      foreignTable: contabb      # Tabla foranea
      foreignReference: codcta   # Campo de la tabla foranea
      description: Cuenta Contable
    numasi:
      type: NUMERIC
      size: 3
    refasi:
      type: VARCHAR
      size: 8
    desasi:
      type: VARCHAR
      size: 250
    monasi:
      type: NUMERIC
      size: 14
      scale: 2
      description: Monto asignado
    id:
      type: INTEGER
      required: true
      primaryKey: true
      autoIncrement: true
      description: Identificador Único del registro
      description: Identificador Único de la tabla
    _indexes:
      contabc1_index_01: [numcon, codcta, feccom]
  codefcencos:
    codcencos:
      type: VARCHAR
      size: 32
      required: true
    descencos:
      type: VARCHAR
      size: 500
      required: true
    id:
      type: INTEGER
      required: true
      primaryKey: true
      autoIncrement: true
      description: Identificador Único del registro
  codetcencos:
    numcom:
      type: VARCHAR
      size: 8
      required: true
    codcta:
      type: VARCHAR
      size: 32
      required: true
    codcencos:
      type: VARCHAR
      size: 32
      required: true
    moncencos:
      type: NUMERIC
      size: 14
      scale: 2
    id:
      type: INTEGER
      required: true
      primaryKey: true
      autoIncrement: true
      description: Identificador Único del registro
