propel:
  _attributes: { noXsd: false, defaultIdMethod: native, package: lib.model.documentos }
  dfmedtra:
    destra:
      type: VARCHAR
      size: 100
    id:
  dfatendoc:
    nroexp:
      type: INTEGER
      required: true
      autoIncrement: true
    coddoc:
      type: VARCHAR
      size: 30
    desdoc:
      type: VARCHAR
      size: 250
    mondoc:
      type: VARCHAR
      size: 50
    fecdoc:
      type: VARCHAR
      size: 50
    staate:
      type: VARCHAR
      size: 50
    anuate:
      type: INTEGER
      required: true
    estado:
      type: VARCHAR
      size: 1
    id_dftabtip:
      type: INTEGER
      required: true
      foreignTable: dftabtip
      foreignReference: id
    infdoc1:
      type: VARCHAR
      size: 100
    infdoc2:
      type: VARCHAR
      size: 100
    infdoc3:
      type: VARCHAR
      size: 100
    infdoc4:
      type: VARCHAR
      size: 100
    refdoc:
      type: VARCHAR
      size: 100
    id:
  dfatendocdet:
    id_dfatendoc:
      type: INTEGER
      required: true
      foreignTable: dfatendoc
      foreignReference: id
    id_usuario:
      type: INTEGER
      required: true
      foreignTable: usuarios
      foreignReference: id
    desate:
      type: VARCHAR
      size: 100
    fecrec:
      type: TIMESTAMP
      required: true
    fecate:
      type: TIMESTAMP
      required: true
    id_acunidad_ori:
      type: INTEGER
      foreignTable: acunidad
      foreignReference: id
    id_acunidad_des:
      type: INTEGER
      foreignTable: acunidad
      foreignReference: id
    id_dfrutadoc:
      type: INTEGER
      required: true
      foreignTable: dfrutadoc
      foreignReference: id
    id_dfmedtra:     # Medio de Transporte
      type: INTEGER
      foreignTable: dfmedtra
      foreignReference: id
    diaent:          # Dias de entrega
      type: INTEGER
      required: true
    totdia:          # Total de dias para la atencion.
      type: INTEGER
      required: true
    id:
  dfatendocobs:
    desobs:
      type: VARCHAR
      size: 100
    id_dfatendocdet:
      type: INTEGER
      required: true
      foreignTable: dfatendocdet
      foreignReference: id
    id_usuario:
      type: INTEGER
      required: true
      foreignTable: usuarios
      foreignReference: id
    fecobs:
      type: TIMESTAMP
      required: true
  dfrutadoc:
    #_attributes:
      #idMethod: native
    rutdoc:
      type: INTEGER
      required: true
    desuni:
      type: VARCHAR
      size: 100
    desrut:
      type: VARCHAR
      size: 100
    diadoc:
      type: INTEGER
      required: true
    id_acunidad:
      type: INTEGER
      required: true
      foreignTable: acunidad
      foreignReference: id
    id_dftabtip:
      type: INTEGER
      required: true
      foreignTable: dftabtip
      foreignReference: id
    id:
  dftabtip:
    tipdoc:
      type: VARCHAR
      size: 4
      required: true
    nomtab:
      type: VARCHAR
      size: 30
      required: true
    vidutil:
      type: INTEGER
      required: true
    clvprm:
      type: VARCHAR
      size: 30
    clvfrn:
      type: VARCHAR
      size: 30
    mondoc:
      type: VARCHAR
      size: 20
    fecdoc:
      type: VARCHAR
      size: 20
    desdoc:
      type: VARCHAR
      size: 20
    stadoc:
      type: VARCHAR
      size: 20
    nomtabfk:
      type: VARCHAR
      size: 30
    nomcolloc:
      type: VARCHAR
      size: 30
    nomcolfor:
      type: VARCHAR
      size: 30
    infdoc1:
      type: VARCHAR
      size: 100
    infdoc2:
      type: VARCHAR
      size: 100
    infdoc3:
      type: VARCHAR
      size: 100
    infdoc4:
      type: VARCHAR
      size: 100
    valact:
      type: VARCHAR
      size: 1
    valanu:
      type: VARCHAR
      size: 1
    fecini:
      type: DATE
    refdoc:
      type: VARCHAR
      size: 100
    id:
  dfdiafer:
    diafer:
      type: DATE
    id:
    
