generator:
  class:              cidesaPropelAdminGenerator
  param:
    model_class:      Tscheemi
    theme:            cidesaGenerator

    fields:
      grid: { name: . }

    edit:
      title: Actualización de Cheques
      display:
        NONE: [ _grid ]
      actions:
        _save:        ~