generator:
  class:              cidesaPropelAdminGenerator
  param:
    model_class:      Tscheemi
    theme:            cidesaGenerator
    fields:
      grid: { name: . }
    edit:
      title:          Recepción de Cheques sin Firma
      display:
        "Cheques": [_grid]
      hide:  [filasord]
      actions:
        _save:        ~