indexSuccess:
  http_metas:
    content-type: text/html

  metas:
    title:        Roraima - Login
    robots:       index, follow
    description:  Modulo de Autenticacion de Cidesa
    keywords:     cidesa, autenticacion, login
    language:     es_VE

  stylesheets:    [siga, screen-for-login, styles-for-login]

  javascripts:    [ ]

  has_layout:     on
  layout:         layout

