generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Aplifor
    theme:            default
    fields:
      codapl: {name: M贸dulo, params: maxlength=3}
      coddiv: {name: Divisi贸n, params: maxlength=3}
      desopc: {name: Descripci贸n del Formulario, params: maxlength=1000}
      nomopc: {name: Nombre del Formulario, params: maxlength=50}
    list:
      title:          Listado de Formularios
      filters:        [codapl, coddiv, desopc]
      display:        [=codapl, desopc, nomopc]
      object_actions:
        _edit:        ~
        _delete:      ~
      max_per_page:   10
      sort: codapl
    edit:
      title:          Asignaci贸n de Formularios
      display:        [codapl, coddiv, desopc, nomopc]
      actions:
        _list:        ~
        _save:        ~
        _delete:      ~
        _create:      ~