opciones:                  # Opciones generales
  name:                    a
  eliminar:                true
  tabla:                   cpimpcom
  anchogrid:               850
  ancho:                   1090
  filas:                   1
  titulo:                  ' '
  htmltotalfilas:          ' '
1:       # Columna 1
  titulo:                  Código Presupuestario
  tipo:                    t
  nombrecampo:             codpre
  html:                    [size="30" readonly="true" ]
  oculta:                  false
  esgrabable:              false
2:       # Columna 2
  titulo:                  Monto
  tipo:                    m
  nombrecampo:             monimp
  html:                    [size="10" readonly="true" ]
  oculta:                  false
  esgrabable:              false
  estotal:                 [ true, cpprecom_monprc ]
3:       # Columna 3
  titulo:                  Comprometido
  tipo:                    m
  nombrecampo:             moncom
  html:                    [size="10" readonly="true" ]
  esgrabable:              false
  estotal:                 [ true, cpprecom_salcom ]
4:       # Columna 4
  titulo:                  Causado
  tipo:                    m
  nombrecampo:             moncau
  html:                    [size="10" readonly="true" ]
  esgrabable:              false
  estotal:                 [ true, cpprecom_salcau ]
5:       # Columna 5
  titulo:                  Pagado
  tipo:                    m
  nombrecampo:             monpag
  html:                    [size="10" readonly="true" ]
  esgrabable:              false
  estotal:                 [ true, cpprecom_salpag ]
6:       # Columna 6
  titulo:                  Ajuste
  tipo:                    m
  nombrecampo:             monaju
  html:                    [size="10" readonly="true" ]
  esgrabable:              false

