default:
  http_metas:
    content-type: text/html

  metas:
    title:        Catálogo de Datos
    robots:       index, follow
    description:  Catálogo de Datos
    keywords:     catalogo datos
    language:     en

  stylesheets:    [main, catalogo]

  javascripts:    [%SF_PROTOTYPE_WEB_DIR%/js/prototype]

  has_layout:     on
  layout:         layout_generales
