modules/*/config/security.yml:
  class:    cidesaSecurityConfigHandler
modules/generales/config/security.yml:
  class:    sfSecurityConfigHandler
modules/acidetest/config/security.yml:
  class:    sfSecurityConfigHandler
