generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Caentalm
    theme:            default
    fields:
      rcpart:  {  name: Número }
      codalm:  {  name: Código Almacen }
      codpro:  {  name: CI/RIF Contratistas de Bienes o Servicio y Cooperativas }
      rifpro:  {  name: CI/RIF Contratistas de Bienes o Servicio y Cooperativas }
      desrcp:  {  name: Descripción }
      tipmov:  {  name: Tipo Movimiento }
      fecrcp:  {  name: Fecha, params: date_format='dd/MM/yyyy' }
      monrcp:  {  name: Monto Total}
      codubi:      { name: Código de la Ubicación}
      codcen: { name : Centro de Costo}
    list:
      title:   Entradas en el Almacen
      display:        [=rcpart, desrcp, monrcp, fecrcp]
      filters: [rcpart, rifpro, fecrcp, codcen]
      object_actions:
        _edit:        ~
        _delete:      NONE
      max_per_page:   10
      sort:    rcpart
    edit:
      title:   Entradas en el Almacen
      display:        [=rcpart, codalm, codpro, desrcp, monrcp, tipmov, fecrcp, codubi, codcen]
      actions:
        _list:        ~
        _save:        ~
        _delete:      ~
        _create:      ~