generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Carecarg
    theme:            default

    fields:
      codrgo: { name: C贸digo}
      nomrgo: { name: Descripci贸n}
      tiprgo: { name: Tipo de Recargo}
      monrgo: { name: Valor}
      codpre: { name: C贸digo}
      nompre: { name: Nombre}
      codcta: { name: Codigo}
      descta: { name: Nombre}

    list:
      title:          Recargos
      display:        [=codrgo, nomrgo]
      filters:		  [codrgo, nomrgo]
      max_per_page:	  10
      sort:           codrgo
      object_actions:
        _edit:        ~
        _delete:      ~
    edit:
      title:          Edici贸n de Recargos
      display:        [codrgo, nomrgo, tiprgo, monrgo, codpre, nompre, codcta, descta]
      actions:
        _list:        ~
        _save:        ~
        _delete:      ~
        _create:      ~