generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Catipsal
    theme:            default
    fields:
      codtipsal:  {  name: C贸digo, params: maxlength=3}
      destipsal:  {  name: Descripci贸n, params: maxlength=50}
    list:
      title:          Definici贸n de Tipos de Salida
      display:        [=codtipsal, destipsal]
      filters:        [codtipsal, destipsal]
      object_actions:
        _edit:        ~
        _delete:      ~
      max_per_page:   10
      sort:           codtipsal
    edit:
      title:          Edici贸n Tipos de Salida
      display:		  [codtipsal, destipsal]
      actions:
        _list:        ~
        _save:        ~
        _delete:      ~
        _create:      ~