generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Fortipfin
    theme:            default
    fields:
      codfin: { name: Código}
      nomext: { name: Nombre Extendido}
      nomabr: { name: Nombre Abreviado}

    list:
      title:          Tipos de Financiamiento
      filters:        [codfin]
      display:        [=codfin, nomext, nomabr]
      sort:           codfin
      object_actions:
        _edit:        ~
        _delete:      ~
      max_per_page:   5
    edit:
      title:          Edición de Tipos de Financiamiento
      display:        [=codfin, nomext, nomabr]
      actions:
        _list:        ~
        _save:        ~
        _create:      ~
        _delete:      ~