opciones:                  # Opciones generales
  name:                    compromiso
  eliminar:                false
  tabla:                   casolart
  anchogrid:               820
  ancho:                   820
  filas:                   0
  titulo:                  ' '
  htmltotalfilas:          ' '
1:       # Columna 1
  titulo:                  Actualizar
  tipo:                    k
  nombrecampo:             check
  html:                    ["size=3 onClick=validar(this.id)"]
  esgrabable:              true
2:       # Columna 2
  titulo:                  Referencia
  tipo:                    t
  nombrecampo:             reqart
  html:                    [size="10" ]
  esgrabable:              true
3:       # Columna 3
  titulo:                  Descripcion
  tipo:                    a
  nombrecampo:             desreq
  html:                    [size="40x2" ]
  esgrabable:              false
4:       # Columna 4
  titulo:                  Fecha
  tipo:                    f
  nombrecampo:             fecreq
  html:                    [size="10"]
  esgrabable:              false
5:       # Columna 5
  titulo:                  Monto
  tipo:                    m
  nombrecampo:             monreq
  html:                    [size="10" ]
  esgrabable:              false
6:       # Columna 6
  titulo:                  Analista de Compras
  tipo:                    t
  nombrecampo:             codemp
  html:                    [size="15" readonly=true]
  esgrabable:              true
  catalogo:                [nphojint, sf_admin_edit_form, {Codemp: 6, Nomemp: 7}, Nphojint_Almordcom ]
7:       # Columna 7
  titulo:                  Nombre
  tipo:                    t
  nombrecampo:             nomemp
  html:                    [size="25" readonly=true]
  esgrabable:              true
8:       # Columna 8
  titulo:                  Observación
  tipo:                    a
  nombrecampo:             obsreq
  html:                    [size="40x2" ]
  esgrabable:              true