generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Cadefubi
    theme:            default
    fields:
      codubi:  {  name: C贸digo, params: maxlength=20}
      nomubi:  {  name: Descripci贸n, params: maxlength=100}
    list:
      title:          Definici贸n de Ubicaciones
      display:        [=codubi, nomubi]
      object_actions:
        _edit:        ~
        _delete:      ~
      filters:        [codubi, nomubi]
      max_per_page:   10
      sort:  codubi
    edit:
      title:          Definici贸n de Ubicaciones
      display:        [codubi, nomubi]
      actions:
        _list:        ~
        _save:        ~
        _delete:      ~
        _create:      ~