default:
  http_metas:
    content-type: text/html

  metas:
    title:        Roraima - Login
    robots:       index, follow
    description:  symfony project
    keywords:     symfony, project
    language:     en_US

  stylesheets:    [siga, estilos]

  javascripts:    [ %SF_PROTOTYPE_WEB_DIR%/js/prototype, %SF_PROTOTYPE_WEB_DIR%/js/scriptaculous, tools, ajax, observe]

  has_layout:     on
  layout:         layout_cidesa
