opciones:                  # Opciones generales
  name:                    c
  eliminar:                false
  tabla:                   atdetrecayu
  anchogrid:               750
  ancho:                   300
  filas:                   0
  titulo:                  ' '
  htmltotalfilas:          ' '
1:       # Columna 1
  titulo:                  Entregado
  tipo:                    k
  nombrecampo:             entregado
  html:                    [size="40" ]
  esgrabable:              true
2:       # Columna 2
  titulo:                  Recaudo
  tipo:                    t
  nombrecampo:             desrec
  html:                    [size="50" readonly="true" ]
3:       # Columna 3
  titulo:                  Código Recaudo
  tipo:                    t
  nombrecampo:             Recaudid
  html:                    [size="10" readonly="true"]
  oculta:                  true
  esgrabable:              true
4:       # Columna 4
  titulo:                  Requerido
  tipo:                    t
  nombrecampo:             requerido
  html:                    [size="10" readonly="true"]
  esgrabable:              false



