opciones:                  # Opciones generales
  name:                    b
  eliminar:                true
  tabla:                   atdetayu
  anchogrid:               900
  ancho:                   860
  filas:                   7
  titulo:                  ' '
  htmltotalfilas:          ' '
1:       # Columna 1
  titulo:                  Aprobado
  tipo:                    k
  nombrecampo:             aprobado
  html:                    [ size="2" ]
  esgrabable:              true
2:       # Columna 1
  titulo:                  atgrudonid
  tipo:                    t
  nombrecampo:             atgrudonid
  html:                    [ '' ]
  oculta:                  true
  esgrabable:              false
3:       # Columna 2
  titulo:                  Grupo
  tipo:                    t
  nombrecampo:             codgru
  html:                    [size="4" ]
  esgrabable:              false
  oculta:                  true
4:       # Columna 2
  titulo:                  Descripción
  tipo:                    t
  nombrecampo:             desgru
  html:                    [ '' ]
  esgrabable:              false
  oculta:                  true
5:       # Columna 3
  titulo:                  atdonaciones_id
  tipo:                    t
  nombrecampo:             atdonaciones_id
  html:                    [ '' ]
  oculta:                  true
  esgrabable:              true
6:       # Columna 4
  titulo:                  Donación
  tipo:                    t
  nombrecampo:             coddon
  html:                    [size="6" ]
  oculta:                  false
  esgrabable:              true
  ajaxfila:                true
7:       # Columna 4
  titulo:                  Descripción
  tipo:                    t
  nombrecampo:             desdon
  html:                    [size="18" readonly="true" ]
  oculta:                  false
  esgrabable:              true
8:       # Columna 6
  titulo:                  Cantidad
  tipo:                    m
  nombrecampo:             cantidad
  html:                    [size="4" readonly="true" ]
  esgrabable:              true
  esnumerico:              true
9:       # Columna 7
  titulo:                  Cantidad Aprobada
  tipo:                    m
  nombrecampo:             canapr
  html:                    [size="6" ]
  esgrabable:              true
  esnumerico:              true
  ajaxfila:                true
10:       # Columna 8
  titulo:                  Precio Aprobado
  tipo:                    m
  nombrecampo:             precio
  html:                    [size="10" ]
  esgrabable:              true
  esnumerico:              true
  ajaxfila:                true
11:       # Columna 8
  titulo:                  Total Aprobado
  tipo:                    m
  nombrecampo:             totapr
  html:                    [size="10" ]
  esgrabable:              true
  esnumerico:              true
  estotal:                 [true, atayudas_monapr]
12:       # Columna 6
  titulo:                  Unidad
  tipo:                    t
  nombrecampo:             unidad
  html:                    [size="4" ]
  oculta:                  false
  esgrabable:              true


