generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Caprovee
    theme:            default

    fields:
      codpro:       { name : Código}
      nompro:       { name : Nombre}
      rifpro:       { name : C.I./RIF}
      nitpro:       { name : Tipo}
      dirpro:       { name : Dirección}
      telpro:       { name : Teléfono}
      nrocei:       { name : Nro.RNC}
      email:        { name : Correo Electrónico}
      codram:       { name : Ramo}
      nomram:       { name : Nombre del Ramo}
      limcre:       { name : Limite de Crédito}
      codcta:       { name : Cta. Contable Asoc.}
      descta:       { name : Descripción}
      codord:       { name : Cta. de Orden Asoc.}
      desctacodord: { name : Descripción}
      codpercon:    { name : Cta.PerContra Asoc.}
      desctacodpercon: { name : Descripción}
      fecinscir:    { name : Fecha de Inscripción}
      faxpro:       { name : Fax}
      numinscir:    { name : Circunscripción Judicial}
      regmer:       { name : Registro Mercantil}
      tomreg:       { name : Tomo}
      capsus:       { name : Capital Suscrito}
      fecreg:       { name : Fecha Reg}
      folreg:       { name : Folio}
      cappag:       { name : Capital Pagado}
      fecven:       { name : Fecha Venc}
      rifrepleg:    { name : C.I./R.I.F.}
      nomrepleg:    { name : Nombre}
      dirrepleg:    { name : Dirección}
      telrepleg:    { name : Teléfono}
      codtiprec:    { name : Grupo}
      destiprec:    { name : Descripción}
      griprecaudos:    { name : . }
      gripcontactos:   { name : . }
      gripramos:       { name : . }
      ramgen:          { name : Ramo General, params: size=20x2}
      nacpro:       { name : Nacionalidad}
      tipo:         { name : Actividad Principal}
      codctasec:    { name : Cta. Contable Asoc}
      desctacodctasec:    { name : Descripción}
      codordadi:          { name : Cta. de Orden Asoc}
      desctacodordadi:    { name : Descripción}
      codperconadi:       { name : Cta. PerContra Asoc}
      desctacodperconadi: { name : Descripción}
      codordmercon:       { name : Cta. de Orden}
      desctacodordmercon: { name : Descripción}
      codpermercon:       { name : Cta. PerContra}
      desctacodpermercon: { name : Descripción}
      codordcontra:       { name : Cta. de Orden}
      desctacodordcontra: { name : Descripción}
      codpercontra:       { name : Cta. PerContra}
      desctacodpercontra: { name : Descripción}
      recargo:            { name : Recaudos}
      codtipemp:          { name : Tipo de Empresa}
      destip:             { name : Descripción}
      gripretenciones:       { name : . }
      estpro:             { name : Estatus}
      codban:             { name : Banco}
      codtip:             { name : Tipo de Cuenta}
      numcue:             { name : Numero de Cuenta}

    list:
      title:          Registro de Contratistas de Bienes o Servicio y Cooperativas
      display:        [=codpro, nompro, rifpro]
      filters:		  [codpro, nompro, rifpro]
      max_per_page:	  10
      sort:           codpro
      fields:
        codpro:      { params : maxlength=15 }
      object_actions:
        _edit:        ~
        _delete:      ~
    edit:
      title:          Edición de Contratistas de Bienes o Servicio y Cooperativas
      display:
        NONE:         [codpro, nompro, rifpro, nitpro, dirpro, telpro, nrocei, email, codram, nomram, limcre, codcta, descta, codord, desctacodord, codpercon, desctacodpercon, fecinscir, estpro, faxpro, numinscir, regmer, tomreg, capsus, fecreg, folreg, cappag, fecven, rifrepleg, nomrepleg, dirrepleg, codtiprec, destiprec, nacpro, tipo, codctasec, desctacodctasec, codordadi, desctacodordadi, codperconadi, desctacodperconadi, codordmercon, desctacodordmercon, codpermercon, desctacodpermercon, codordcontra, desctacodordcontra, codpercontra, desctacodpercontra, recargo, codtipemp, destip, telrepleg, _codban, numcue, _codtip]
        Recaudos:     [_codtiprec, _griprecaudos]
        Contactos:    [ _gripcontactos]
        Ramos:        [ _gripramos, ramgen]
        Retenciones:        [ _gripretenciones]

      #fields:
      #  recargo:    { type: admin_double_list, params: through_class=Carecpro}
      actions:
        _list:        ~
        _save:        ~
        _delete:      ~
        _create:      ~
