generator:
  class:              cidesaPropelAdminGenerator
  param:
    model_class:      Cpdoccom
    theme:            cidesaGenerator
    fields:
      tipcom: {name: Tipo de Documento, params: onblur=convertirMayusculas(this.id) maxlength=4 size=5}
      nomext: {name: Nombre Extendido}
      nomabr: {name: Nombre Abreviado, params: onblur=convertirMayusculas(this.id) maxlength=4 size=5}
      refprc: {name: Refiere a Precompromiso}
      reqaut: {name: Requiere autorización para su Causado}
      afeprc: {name: .}
      afecom: {name: .}
      afedis: {name: .}
    list:
      title:   Compromisos
      display: [=tipcom, nomext]
      filters: [tipcom, nomext]
    edit:
      title:                     Compromisos
      display:
        Datos del Documento:     [tipcom, nomext, nomabr, _refprc, _reqaut]
        Precompromiso:           [_afeprc]
        Compromiso:              [_afecom]
        Disponibilidad:          [_afedis]
      hide:   [etadef]
      actions:
        _list:        ~
        _save:        ~
        _create:       ~
        _delete:      ~