opciones:                  # Opciones generales
  name:                    b
  eliminar:                true
  tabla:                   atdetayu
  anchogrid:               750
  ancho:                   720
  filas:                   7
  titulo:                  ' '
  htmltotalfilas:          ' '
1:       # Columna 1
  titulo:                  Aprobado
  tipo:                    k
  nombrecampo:             aprobado
  html:                    [ disabled="true" ]
  esgrabable:              true
2:       # Columna 2
  titulo:                  atgrudonid
  tipo:                    t
  nombrecampo:             atgrudonid
  html:                    [ '' ]
  oculta:                  true
  esgrabable:              false
3:       # Columna 3
  titulo:                  Grupo
  tipo:                    t
  nombrecampo:             desgru
  html:                    [ '' ]
  oculta:                  true
  esgrabable:              false
4:       # Columna 4
  titulo:                  atdonaciones_id
  tipo:                    t
  nombrecampo:             atdonaciones_id
  html:                    [ '' ]
  oculta:                  true
  esgrabable:              true
5:       # Columna 5
  titulo:                  Donación
  tipo:                    t
  nombrecampo:             desdon
  html:                    [size="16" readonly="true" ]
  oculta:                  false
  esgrabable:              true
  #catalogo:                [ atdonaciones, sf_admin_edit_form, { id: 3 , desdon: 4 }, Atdonaciones_Aciayudas ]
6:       # Columna 6
  titulo:                  Cantidad
  tipo:                    m
  nombrecampo:             cantidad
  html:                    [size="5" readonly="true" ]
  esgrabable:              true
  esnumerico:              true
7:       # Columna 7
  titulo:                  Cantidad Aprobada
  tipo:                    m
  nombrecampo:             canapr
  html:                    [size="5" readonly="true" ]
  esgrabable:              true
  esnumerico:              true
8:       # Columna 8
  titulo:                  Precio
  tipo:                    m
  nombrecampo:             precio
  html:                    [size="5" readonly="true" ]
  esgrabable:              true
  esnumerico:              true


