generator:
  class:              cidesaPropelAdminGenerator
  param:
    model_class:      Bdcriterio
    theme:            cidesaGenerator
    fields:
      grid:           { name: .   }
    edit:
      title:          Chequear Base de Datos
      display:        [_grid]
      hide:           [numfilas]
      actions:
        _list:       NONE
        _save:       NONE
        _delete:     NONE
        _create:     NONE