generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Caforent
    theme:            default

    fields:
      codforent:      { name : Código, params: maxlength=4}
      desforent:      { name : Descripción}

    list:
      title:          Tiempo de Entrega
      display:        [=codforent, desforent]
      object_actions:
        _edit:        ~
        _delete:      ~
      filters:       [codforent, desforent]
#        - codforent
#        - desforent
      fields:
        codforent: { params: maxlength=4}
        desforent:

      max_per_page:	  10
      sort:    codforent
    edit:
      title:          Edición de Tiempo de Entrega
      display:        [codforent, desforent]
      actions:
        _list:        ~
        _save:        ~
        _delete:      ~
        _create:      ~