generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Tsmovlib
    theme:            default
    fields:
      numcue: { name: Cuenta del Banco}
      nomcue: { name: d}
      reflib: { name: Referencia}
      feclib: { name: Fecha del Movimientos, params: date_format='dd/MM/yyyy'}
      tipmov: { name: Tipo}
      destip: { name: d}
      deslib: { name: Descripcion}
      fecing: { name: Fecha del Registro, params: date_format='dd/MM/yyyy'}
      monmov: { name: Monto}
      numcom: { name: Numero de Comprobante}
      feccom: { name: Fecha, params: date_format='dd/MM/yyyy'}
      status: { name: Estatus}
      stacon: { name: Estatus Contable}
      refpag: { name: Referencia del Pagado}
      cedrif: { name: C.I. o Rif Beneficiario, params: maxlength=15}



    list:
      title:          Movimientos Segun Libros
      filters:        [numcue, reflib, feclib, tipmov, deslib, cedrif]
      display:        [=numcue, reflib, tipmov, deslib, feclib]
      sort:           numcue
      object_actions:
        _edit:        ~
      max_per_page:   10
      options:        [ tipmov, numcue]
    edit:
      title:          Movimientos Segun Libros
      display:       [=numcue, nomcue, reflib, feclib, tipmov, destip, deslib, monmov, fecing, numcom, feccom, debcre, codcta, status, stacon, refpag, cedrif]
      actions:
        _list:        ~
        _save:        ~
        _create:        ~
        _delete:      ~
