generator:
  class:              cidesaPropelAdminGenerator
  param:
    model_class:      Cpasiini
    theme:            cidesaGenerator
    fields:
      codpre:  {name: Código}
      nompre:  {name: Descripción, params: readOnly=true size=80}
      anopre:  {name: Año, params: readOnly=true size=5}
      asiper:  {name: Asignación Períodica}
      monasi:  {name: Monto Asignar, params: size=12}
      grid:    { name: . }
    list:
      fields:
        codpre: {name: Código Presupuestario, params: key_method="getCodpre"}
      title:  	      Asignaciones Iniciales
      display:        [=codpre, nompre]
      filters:        [codpre, nompre]
      sort: codpre
      actions:
        _create:        ~
    edit:
      title:  			                   Asignación Inicial
      display:
        Datos del Código Presupuestario:   [_codpre, nompre]
        Datos de la Asignación:            [anopre, _asiper, _monasi]
        NONE:						  	   [_grid]
      hide:  [numper]
      actions:
        _list:        ~
        _save:        ~
        _create:      ~
        _delete:      NONE