opciones:                  # Opciones generales
  name:                    a
  eliminar:                false
  tabla:                   cpimpcom
  anchogrid:               850
  ancho:                   1090
  filas:                   0
  titulo:                  ' '
  htmltotalfilas:          ' '
1:       # Columna 1
  titulo:                  Código Presupuestario
  tipo:                    t
  nombrecampo:             codpre
  html:                    [size="30" readonly="true" ]
  oculta:                  false
  esgrabable:              false
2:       # Columna 2
  titulo:                  Monto
  tipo:                    m
  nombrecampo:             monimp
  html:                    [size="10" readonly="true" ]
  oculta:                  false
  esgrabable:              false
3:       # Columna 3
  titulo:                  Causado
  tipo:                    m
  nombrecampo:             moncau
  html:                    [size="10" readonly="true" ]
  esgrabable:              false
4:       # Columna 4
  titulo:                  Pagado
  tipo:                    m
  nombrecampo:             monpag
  html:                    [size="10" readonly="true" ]
  esgrabable:              false
5:       # Columna 5
  titulo:                  Disponibilidad
  tipo:                    m
  nombrecampo:             mondis
  html:                    [size="10" readonly="true" ]
  esgrabable:              false
6:       # Columna 6
  titulo:                  Ajuste
  tipo:                    m
  nombrecampo:             monaju
  html:                    [size="10" readonly="true" ]
  esgrabable:              false
7:       # Columna 7
  titulo:                  Referencia
  tipo:                    t
  nombrecampo:             refere
  html:                    [size="8" readonly="true" ]
  esgrabable:              false
