opciones:                  # Opciones generales
  name:                    a
  eliminar:                false
  tabla:                   contabb1
  anchogrid:               750
  ancho:                   700
  filas:                   0
  titulo:                  ' '
  htmltotalfilas:          ' '
1:       # Columna 1
  titulo:                  Período
  tipo:                    t
  nombrecampo:             pereje
  html:                    [size="3" readonly="true"]
  oculta:                  false
  esgrabable:              true
2:       # Columna 2
  titulo:                  Débito
  tipo:                    m
  nombrecampo:             totdeb
  html:                    [size="10" readonly="true"]
  oculta:                  false
  esgrabable:              true
3:       # Columna 3
  titulo:                  Crédito
  tipo:                    m
  nombrecampo:             totcre
  html:                    [size="10" readonly="true"]
  esgrabable:              true
4:       # Columna 4
  titulo:                  Saldo del Período
  tipo:                    m
  nombrecampo:             salper                                 #la vamos a crear porq no esta en esa tabla
  html:                    [size="10" readonly="true"]
  esgrabable:              true
5:       # Columna 5
  titulo:                  Saldo Actual
  tipo:                    m
  nombrecampo:             salact
  html:                    [size="10" readonly="true" onBlur=actualizarSaldos(this);]
  esgrabable:              true
6:       # Columna 6
  titulo:                  Saldo Programado
  tipo:                    m
  nombrecampo:             salprgper
  html:                    [size="10" readonly="true"]
  esgrabable:              true
7:       # Columna 7
  titulo:                  Saldo Acumulado
  tipo:                    m
  nombrecampo:             salacu                                 #la vamos a crear porq no esta en esa tabla
  html:                    [size="8" readonly="true"]
  esgrabable:              true
