generator:
  class:              cidesaPropelAdminGenerator
  param:
    model_class:      Atayudas
    theme:            cidesaGenerator

    fields:
      expediente:          { name: Nro. de Expediente, params: disabled=true size=6 }
      atsolici:
        name: Cédule Solicitante
      atbenefi:
        name: Cédula Paciente/Beneficiario
      attipayu_id:
        name: Grupo de Rubros
        params:     text_method=getDesayu onchange=toAjaxUpdater('divrubros',5,getUrlModulo()+'ajax',this.value,'','');
      atrubros_id: { name: Rubro }
      caprovee_id: { name: Proveedor }
      cedula:      { name: Cedula }
      desayu:      { name: Observación, type: textarea_tag, params: cols=60 rows=2 rich=false }
      motayu:      { name: Motivo, type: textarea_tag, params: cols=60 rows=2 rich=false }
      detalleayudas: {name: Detalle Ayuda}
      detallerecaudos: {name: Detalle Recaudos}
      detayu:      { name: Detalle }
      atmedico_id:      { name: Médico Tratante }
      respat:   { name: Diagnóstico, type: textarea_tag, params: size=70x3 maxlength=5000 }
      infmed:   { name: Informe Médico, type: textarea_tag, params: size=70x3 maxlength=5000 }
      obsmed:   { name: Observación, type: textarea_tag, params: size=70x3 maxlength=5000 }
      fecdiasoc:     { name: Fecha Informe }
      usudiasoc:     { name: Elaborado Por, params: size=100 maxlength=100 }
      resdiasoc:    { name: Resumen Patología, type: textarea_tag, params: size=70x3 maxlength=5000 }
      fecvisdoc:     { name: Fecha }
      usuvisdoc:     { name: Elaborado Por, params: size=100 maxlength=100 }
      resvisdoc:   { name: Resumen, type: textarea_tag, params: size=70x3 maxlength=5000 }
      monayu:    { name: Monto en Bolívares (Bs.)}
      fecsol:     { name: Fecha }
      refdoc:     { name: Orden de Pago }
      priayu:     { name: Prioridad de Atención }
      atpriayu_id:     { name: Prioridad de Atención, params: include_blank=false }
    list:
      title:          Solicitud de Ayudas
      display:        [=id, =nombre, desayu]
      object_actions:
        _edit:        ~
        _delete:      ~
      filters:        [id, atsolici, attipayu]
      max_per_page:   5
      #sort:           atsolici_id
    edit:
      title:          Edición de Solicitud de Ayuda
      display:
        Expediente:   [ _expediente, fecsol ]
        Solicitante:  [_atbenefi, _atsolici, _parentesco]
        Prioridad:    [atpriayu_id]
#        Proveedor:    [_caprovee_id]
        Ayuda:        [attipayu_id, _atrubros_id, desayu]
        Detalle de Recaudos: [_detallerecaudos]
        Diagnostico Médico: [fecdiasoc, _atmedico_id, resdiasoc]
        Diagnostico Social: [respat, obsmed]
#        Informe de Visita Domiciliaria: [fecvisdoc, usuvisdoc, resvisdoc]
        Detalle de Ayuda: [_detalleayudas]
#        Detalle de Ayuda: [_detayu]
        Monto Total de la Ayuda Solicitada: [monayu]
      report:
        url:         ciudadanos/r.php?m=ciudadanos&r=atfichareg.php
        params:      { numexpdes: nroexp, numexphas: nroexp }
      actions:
        _save:        ~
        _create:      ~
