generator:
  class:              cidesaPropelAdminGenerator
  param:
    model_class:      Usuarios
    theme:            cidesaGenerator

    fields:
      loguse: {name: Usuario, params: size=7 readonly=true }
      nomuse: {name: Nombre Usuario, params: size=20 readonly=true }
      pasuse: {name: Contrase単a Actual, params: size=15 type=password }
      password: {name: Nueva Contrase単a, params: size=15 }
      repassword: {name: Validar Contrase単a, params: size=15 }


    edit:
      title:          Cambiar Contrase単a
      display:        [loguse, nomuse, pasuse, _password, _repassword]
      actions:
        _save:        ~
