default:
  http_metas:
    content-type: text/html

  metas:
    title:        Módulo Presupuesto
    robots:       modulo, presupuesto
    description:  Módulo de Presupuesto
    keywords:     Módulo, Presupuesto
    language:     en

  stylesheets:    [main]

  javascripts:    [ %SF_PROTOTYPE_WEB_DIR%/js/prototype, %SF_PROTOTYPE_WEB_DIR%/js/scriptaculous, tools, ajax, presupuesto/prenivpre, observe]

  has_layout:     on
  layout:         layout
