generator:
  class:              cidesaPropelAdminGenerator
  param:
    model_class:      Empresa
    theme:            cidesaGenerator
    fields:
      codemp:      {name: Usuario Origen}
      codempdes:   {name: Usuario Destino, params: size=5 maxlength=3 disabled=false}      
      info:   {name: .}
    edit:
      title:          Actualizar Saldos Contables
      display:        [_codemp, _codempdes, _info]
      actions:
        _save:
          name: Aceptar
          params:  confirm=Esta Seguro que desea Trasladar los Saldos al Nuevo Periodo?